### ISSUE TITLE
YouTube not working

### ISSUE THREAD

**Issue by GameMaster2030** [alxhotel/chromecast-api#48] opened 2020-06-11 18:23 UTC
I can't get YouTube to work, this is the error I'm getting:
```
self.playlistId = PLAYLIST_ID_REGEX.exec(body)[1]
TypeError: Cannot read property '1' of null
```
Seems to be coming from `youtube-remote`

Code I'm using:
```js
const ChromecastAPI = require('chromecast-api');

const client = new ChromecastAPI();

client.on('device', function (device) {
    console.log(device);
    if (device.name !== "Google-Nest-Mini-[ID]._googlecast._tcp.local") return;
    const mediaURL = 'https://youtube.com/watch?v=[ID]';

    device.play(mediaURL, function (err) {
        if (!err) console.log('Playing in your chromecast');
    });
});
```

**Comment by GameMaster2030** [comment] 2020-06-12 14:00
Nevermind, already built my own solution for this problem.

**Comment by alxhotel** [comment] 2020-06-14 14:01
Hi @GameMaster2030,

Thanks for reporting this!

It looks like a bug. I'll try to reproduce it and give my feedback.

May I asked how did you manage to fix it?

Thanks :)

**Comment by GameMaster2030** [comment] 2020-06-14 14:18
Hi, I didn't fix it, I just built my own workaround that was more logical in my project(downloading the videos and host them on a local wrbserver).

**Comment by alxhotel** [comment] 2020-06-14 15:47
Ah nice!

Ok, I will set this as a bug and check it out later.

**Comment by alxhotel** [comment] 2020-08-01 17:35
Fixed in https://github.com/alxhotel/youtube-remote/commit/b7fa01a30599ef4067c78a54e5436cc248b5360d

**Closed by alxhotel** 2020-08-01 17:35 UTC
Labels: bug

**Comment by choccy** [comment] 2020-09-26 15:33
I seem to be experiencing this bug as well.

**Comment by alxhotel** [comment] 2020-09-26 15:49
Hi @choccy,

Thanks. Can you share more details on this bug?

**Comment by choccy** [comment] 2020-09-28 13:17
Sorry for the late reply.

With this example code:

```
const ChromecastAPI = require('chromecast-api')

const client = new ChromecastAPI()

client.on('device', function (device) {
  if (device.friendlyName === 'Khalid Speaker') {
    device.play('https://www.youtube.com/watch?v=qVdPh2cBTN0', function (err) {
       if (err) { 
         console.error(err)
       } else {
        console.log('Playing in your chromecast'); 
       }
    })
  }
})
```

The output:

```
TypeError: Cannot read property '1' of null
    at C:\Users\Faisal\Documents\Code\cc\node_modules\youtube-remote\index.js:153:55
    at onDone (C:\Users\Faisal\Documents\Code\cc\node_modules\youtube-remote\index.js:269:9)
    at C:\Users\Faisal\Documents\Code\cc\node_modules\youtube-remote\index.js:261:9
    at done (C:\Users\Faisal\Documents\Code\cc\node_modules\needle\lib\needle.js:468:14)
    at PassThrough.<anonymous> (C:\Users\Faisal\Documents\Code\cc\node_modules\needle\lib\needle.js:719:9)
    at PassThrough.emit (events.js:310:20)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Playing in your chromecast
```
